image: python:3.10

stages:
  - lint
  - test

lint-job:
  stage: lint
  script:
    - echo "Installing dependencies..."
    - pip install -r requirements.txt
    - echo "Running linter..."
    - python -m flake8 .

test-job:
  stage: test
  script:
    - echo "Installing dependencies..."
    - pip install -r requirements.txt
    - echo "Running tests..."
    - python -m pytest